service: sls-training

plugins:
  - serverless-offline
  - serverless-plugin-include-dependencies
  - serverless-dotenv-plugin

frameworkVersion: ">=1.21.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs10.x
  region: us-east-1
  environment:
    APP_STATE: ${env:APP_STAGE, 'production'}
    TABLE_SKILLS: ${env:TABLE_SKILLS, ssm:TABLE_SKILLS}

package:
  individually: true
  exclude:
    - ./**

functions:
  ${file(./functions/skills/deploy.yml)}

custom:
  serverless-offline:
    port: ${env:PORT}